/* XPM */
static const char *jxqynys_xpm[] = {
/* width height num_colors chars_per_pixel */
"    96    96      256            2",
/* colors */
"`` c #040204",
"`. c #848584",
"`# c #845950",
"`a c #c4c4c3",
"`b c #354244",
"`c c #c48a74",
"`d c #c4a89c",
"`e c #3c1a1c",
"`f c #646564",
"`g c #c87e6c",
"`h c #846e60",
"`i c #5c453b",
"`j c #e4e5e5",
"`k c #9ca2a4",
"`l c #e4a890",
"`m c #e4c2ac",
"`n c #5c5248",
"`o c #242423",
"`p c #a4867c",
"`q c #a4725d",
"`r c #f48a6c",
"`s c #3c302c",
"`t c #c4967d",
"`u c #ecd2bc",
"`v c #542e2c",
"`w c #241614",
"`x c #a49294",
"`y c #ac5e64",
"`z c #e4b99b",
"`A c #c4bebc",
"`B c #745346",
"`C c #d49981",
"`D c #847e7d",
"`E c #744d41",
"`F c #846355",
"`G c #f4c3a7",
"`H c #3c3c3d",
"`I c #141314",
"`J c #d4a98d",
"`K c #5c4b41",
"`L c #4c524c",
"`M c #f4be9f",
"`N c #2c3634",
"`O c #b4846f",
"`P c #a47b65",
"`Q c #946f5e",
"`R c #747474",
"`S c #acb2b4",
"`T c #f4caa9",
"`U c #d4d5d4",
"`V c #ecf2f4",
"`W c #d4b29c",
"`X c #949494",
"`Y c #4c4543",
"`Z c #2c2d2c",
"`0 c #f4d5ba",
"`1 c #e4bea4",
"`2 c #5c5c5a",
"`3 c #c49e8c",
"`4 c #4c2e28",
"`5 c #94664d",
"`6 c #fcdbbe",
"`7 c #c49278",
"`8 c #b4937e",
".` c #745d53",
".. c #d4a185",
".# c #b48b77",
".a c #947667",
".b c #140a0c",
".c c #945e5c",
".d c #34231c",
".e c #e4b9a4",
".f c #6c4b42",
".g c #4c4c4f",
".h c #845e56",
".i c #dcc5b4",
".j c #746664",
".k c #bca294",
".l c #1c1d1c",
".m c #facebe",
".n c #94837f",
".o c #543b34",
".p c #4c3a32",
".q c #b47b67",
".r c #f4d6cb",
".s c #6c463d",
".t c #fce4c7",
".u c #e4b192",
".v c #a4767c",
".w c #3e3632",
".x c #341e1c",
".y c #856a5e",
".z c #d4b2a9",
".A c #d4927c",
".B c #bc9a7c",
".C c #3c2624",
".D c #acacab",
".E c #6c5449",
".F c #282630",
".G c #c4978e",
".H c #251e22",
".I c #947a6c",
".J c #1c1620",
".K c #644b44",
".L c #9c715f",
".M c #fccbaa",
".N c #cc9275",
".O c #d6a296",
".P c #c4cacc",
".Q c #e4cab4",
".R c #b47669",
".S c #442f29",
".T c #dcaa8e",
".U c #fcfefc",
".V c #54463d",
".W c #bc8e78",
".X c #0c0b0c",
".Y c #8c8c8f",
".Z c #c4b09c",
".0 c #644640",
".1 c #ececeb",
".2 c #2c2522",
".3 c #a48a84",
".4 c #ecba9c",
".5 c #7c534e",
".6 c #8c6559",
".7 c #f4c2bc",
".8 c #443b3b",
"#` c #1c130e",
"#. c #fc7254",
"## c #f49e80",
"#a c #d4b6a4",
"#b c #f4eef4",
"#c c #e4dedc",
"#d c #9c6a62",
"#e c #bcbcbc",
"#f c #d4cdd2",
"#g c #746e6c",
"#h c #fcf2dc",
"#i c #b4aeac",
"#j c #dcbebc",
"#k c #6c6d6c",
"#l c #7c7d7b",
"#m c #dcdcdb",
"#n c #9c9c9c",
"#o c #a49c9a",
"#p c #aca6a8",
"#q c #ac7e84",
"#r c #bcb6bc",
"#s c #6c5a54",
"#t c #948a8c",
"#u c #d48874",
"#v c #643e3c",
"#w c #444344",
"#x c #fcf6fc",
"#y c #946a5c",
"#z c #545a5c",
"#A c #b4827d",
"#B c #342a3c",
"#C c #c4a096",
"#D c #b4a6ac",
"#E c #e4b29e",
"#F c #b49e92",
"#G c #56362f",
"#H c #343a3c",
"#I c #170e10",
"#J c #40221c",
"#K c #a4766c",
"#L c #4c362e",
"#M c #94625d",
"#N c #8c5951",
"#O c #8c7165",
"#P c #ecc3ab",
"#Q c #645651",
"#R c #ac8573",
"#S c #dc9880",
"#T c #8c7a78",
"#U c #7c4d4c",
"#V c #545559",
"#W c #ac7b71",
"#X c #fcd3b6",
"#Y c #645d5c",
"#Z c #bc9480",
"#0 c #7c5b4e",
"#1 c #7c645b",
"#2 c #9c8274",
"#3 c #442a23",
"#4 c #ecbe9f",
"#5 c #9c7668",
"#6 c #8c5e54",
"#7 c #dcb6a1",
"#8 c #a46a5c",
"a` c #0c0604",
"a. c #8c867e",
"a# c #ccc6c4",
"aa c #6c635e",
"ab c #ece6ec",
"ac c #a4a3a2",
"ad c #cc967d",
"ae c #2c1a18",
"af c #fcc6a7",
"ag c #b4b3b4",
"ah c #dcd6dc",
"ai c #f4f4f4",
"aj c #dcaf97",
"ak c #342e24",
"al c #cc9f86",
"am c #dca088",
"an c #ecb8a9",
"ao c #544e4f",
"ap c #5c3b37",
"aq c #fcd3c4",
"ar c #ecb294",
"as c #dcb1a7",
"at c #cc9a94",
"au c #9c7c6e",
"av c #cccccc",
"aw c #ccb0a2",
"ax c #ac8e80",
"ay c #fcc6b4",
"az c #7c6a74",
"aA c #bc867c",
"aB c #cc9e94",
"aC c #84726c",
"aD c #5c4644",
"aE c #5c5654",
"aF c #a4706c",
"aG c #745254",
"aH c #d49a8c",
"aI c #744a4c",
"aJ c #5c4e4c",
"aK c #f4beac",
"aL c #343434",
"aM c #7c7574",
"aN c #f4ccb4",
"aO c #9c9494",
"aP c #4c444c",
"aQ c #5c5e64",
"aR c #4c3234",
"aS c #fcdacc",
"aT c #c49284",
"aU c #b4968c",
"aV c #b48e84",
"aW c #34262c",
"aX c #6c4e4c",
"aY c #4c3e3c",
"aZ c #b47b74",
"a0 c #6c5254",
"a1 c #644e4c",
"a2 c #9c706c",
"a3 c #fcceb4",
"a4 c #cc9084",
"a5 c #eccab4",
"a6 c #442e34",
"a7 c #dca89c",
"a8 c #bc8e84",
/* pixels */
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#b#mavag#o.Y.Y#nac#i`A`Uai.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uabavag#iag`a`j.U.U.U.U.U#f.Y.gaL`o`I.X````````````.X.l`HaMacavai.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.1#o.g`N#`.X````.X.w#Tagaga.#V.l````````````````a`.b``````````````.l`Y.Yac`RaoaP`2.Y`a.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`U.g`````w`w.X.b#I.b````a`#I````````````.X.X.b#``w#`.J.X``#I.X`````````````````````````I`Rah.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`A`Z``.X`w.x#`ae.d`w.b``````.X````````````.b#I#I#`#3ae#I``#I`w#`.X``````.b.X`I`I#I`I`Ia``````o`Xai.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Ua#`o``.b`w.C`w.x#3.x.J````````a```````````a````w`eae`e#3`wa`.bae.J``````#I#`ae.C.d.x.xaW.d#I``a```#Y#m.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#m`N```w`w.x`w.d#3aW#`.X.X.Xa`````a`.b``````````.b`w`e`e#Jae``.b`wa`````.X`w#3a6.o.o#3.x.d.S.C`w#`.b``aL`a.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`f```w.xaW.d.xaW.x`w.b.Xa`````````````.b````````.b`w`e`wae#I``.b````````.l.Hae`w.C`v.o`vak#3`v#3`w#`#I``.lag.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#f`Ia`aW.Cae.d#3.C`w#`.ba```````````````.X.b````````#``e`w#I#```.X``````#`#I``````.b`w.C.o`v#3`v`v#3ae#I#I``.l`A.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`D``ae#3.C.2#3.d.x`w.ba```a```````````````.X.b````````ae`w.b.b````````#I.b````````````.X`w`v#3`v`v`vaWae#I#Ia`aLah.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#c.F.X#3aW.d#3`v.x.2.J.X``````````````````````.X````````.b#I.ba```````.X`````````````````````w.C#3#3`v#3`e#I#`.b``#Yai.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`.``.2#3#JaW#G`v.x`w.b``a```````````````````````.X````````.b.b````````````````````````````````#`#3#3#3#3#3`w#`#`a`a`.D.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#m`Z``#3.SaW`v#vaW`w.J.b``a`````````````````````````````````.b.X```````````````````````````````````e#J.C#J#3.x`w#`.b``aL.1.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#o.X.ba6`4a6.K#vae`w.b.X``a```````````````````````````````````a```````````````````````````````````#Ia6#3#3#3`e`w#I.b````aO.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uai.g```w`v`v.o#U#3#I#`.b````````````````````````````````````````````````````````````````````````````a``e.C#J`e`e`w#`#`a````Zab.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uav`I``aW#v.oaI.0.d#I#`.ba`````````````````````````````````````````````````````````````````````````````#I`e.x`e#3`e`w#I.b``.X#e.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#n``.X.S#v#vaIap`w#`.b.b````````````````````````````````````````````````````````````````````````````````ae.H.C#J#3`w#`.b````#t.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.UaE```w.o#v.saI`4.J#Ia```````````````````````````````````````````.X.X.X.X`I.X.X``.X.X`I.X.X`I.X``````````#I.d.x.C#3`w#I.ba```#w#x.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`j.F``aW#v.0aIaI#J`w.ba```````````````````````````````#I`I````#I.l#``o#VaY.X`I`Z.p`N.X``.X.X.X`I`I````````#`.x.d`e#J`e#`.ba```.lav.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`A.X.b#3#v.saG.0.d#I.b``a```````````````.X.X.l#Va.#k#waa`U#c.Yaa.gaL.H#o.U#laL.Y#j.Y#V#`.l.l.X.X.X````````.b`w.x.d.C`e#`.b.b````#i.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`X```w.o#v.0#N.o`w.b.b``a```````.X`I.laL`Z`I`Z`S.1#ja.`baa`S`U`U#V.w.g`2#k.g`s`N`Z`ba.#l`b.la```#```````````#``wae.d.xae#I.b````aM.U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`f``aW#v.saG#N`v#I.ba`````````.X.X`Iak`Y.w`o`baE#w#z#l`L.X.wa.aQ`Iaaaa.l`````I````.2`f.g.2.X``.X`I#I````````.b`wae`w.x.x#`.ba```.8ai.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#b`H``.S.0.0aGaG#3.b.b````a`#I.X.H#waL#``IaL#l#k#``IaL.w`I``#`.X``a`.b````#``w.b#`.C.Cae#3#3#`#`.J.H`I.b``````.b#``w`w.d`e`w#I.b``.l`U.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`U.l```v#v#vaGaI.C.b``a```.Xa`.X.HaL.F.l.l#B`Z.J`I.J.X#Iae.C#``w.H.d#I.Xae`s.8aDa0.``B.yaF#6`#aRaW.C.C#I.X``````#`ae`w`w.x`w#`#I````ac.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`A.X.b`v#v#vaG.s.H.ba`````#Ia```#I.J#`.J`w#I.b#`.d.o#s.`#OauaJ.o`i.S.Ca6aD.``F#WaA#Wam#S#S.A`C.q`Q`F#s#`#I``````.b#I#Iae`wae#I#`a```.j.U.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uac``#``v#v#v`E.0.x.b````a``wa`.J`oaW.S.V#G.V.S#1`p.Gas#7as#4aj#O`Q`8aD.V.`.hala7#y.A#uamam.u`l.u.u`C.q#Lae````a`.b#`#I#`ae`w#`#Ia```.8ab.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`D``#I.o#v.0aG.s.Ha`````a`.b.X`wa6.paGa2#1.`aGa4ay.m`6.r`T`GaN.Mau#4#Z#QaX`B.4`t`c#S`l.uarar`M`z`z`l...L.p.Xa`````#`#`#Iae`w#I#`.b``#`av.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.UaE```w.o.0.saG#v`wa`````.b`I#I`4aGa1#da7#A#O#d.Oay.m#X#Xa3aN.Ma3`1.e`1au#5`J`Gad.A.uarar.4`G`M`G#4ar`l..#6`Ia`````#`#`#I#`.xae#I.b````.D.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.UaiaL``aeap.V.0a0.o`w``````.X#I`w.oaG.s#qan#7.a#5as.m#Xa3#Xa3.M.M.M.M.M`G`Jad`T`Mamar`M`M`G`M`T#4`G`M.4.u.T`c.S``a```#I#`#I#``w`w#`.b````a..U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uah.l``.d.o.V.0.K.pae``````.X#Iae.0.6#0a8aKaNax.aasaS.m#X.M.M.M`T.Maf.M.M`G`G.M`M`M`M`M#P.M`T`M`T#P`Garar.T#S`i#I````.bae#I.b`w`w#`.b````aa.U.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`a`I``.C.o`i.0.sa6`wa`````#I.baeaGa4.aaB.ma3#7.nasaS.M.M.M`T.M.M.M`T.M.Maf.Mafafaf.M.M.M.M`T`T`T`1.4.4`l.T.W`i`wa```.bae.b.b#``w#`#Ia```.V.1.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uag``.baW.o.o.0.KaR`wa`````#`#``w.0.q#O.Oa5.M#P.I#7aq.Ma3.M.M.M`G.M.M`T.Maf.Maf.Maf.M`T.M`T`T`G`T`M#4ar.T..#W.E`w.X``a``w#`.b#`#I`w#Ia````o#m.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`k``#I.C`v.o.s.0a6ae``````.X#Iae.V`7#Oat.7`TaNaC.zaq#Xa3.M`G.M.M.M.M.M`T.Maf.Maf.M.M`G.M.M.M.M`T`M#4.u.T..`P.K.2.X.b``#I#`.b#I#`#I#`.b```Iav.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`D``#I.d.S.oa1.sa6`wa`````.b#``waD#0`FaU.M.M`T.n#a`6a3a3`T.M.M`T.M`T.Maf.M`T.Maf.M`T.M`T.M#X`T.M`T#4`1.u`J#R.K.da`#Ia`#I#`.b.b#``w.b.b````ag.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#b`2```w.x`v#v.V#vaR`wa`````.b`w.J.V.E#Zax.m#X#X#F#aaq#X`6a3`T.M.M.Maf`T.M.Mafaf.M`T.M.M#X#X`6#X#X#X.M#P.u#Zau.K`4.baea`#I#`.b.b#I#`#`.b````#n.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#m#B```waW.o#v#G#va6.J``.b.b.b.d#`.Vad.I`p.m#X`6aw.Z`6`6`6#X#X.M#X`G`T.M.M`T.M.M`T.M.M#X.M.t`6.t#Xa5`1`W`i.``5#LaR.b#I.b.bae.b.b#I#I#`.ba````R.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.Uav`I```w.C.o#v#G#v#3#Ia`#`.b#IaW#I`K#R.a.I.m`M#X.Q.Z`0.t.t.t`6`0#X#Xa3#X`0`0`0`M`G`1`M#X#X.t.t.t`T#7`B#L#Lak#Laeae.b#`.b.b#I.b.b#`#I#I.b`````n.U.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#e`````w.d`v#v#G#v#3#`a``w.b.b.C#`.VaVaV.aanaj.T`m.za5.t.t.t.t`6`0`0`0`0`0`6`u#4.u`T.M.M.t`6.taN...Eakak`4.S.C#`#`#`#I.b``#I.b.b#I#`.b.ba```aLab.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.Uac````aeae`v.o.oap#J`w``.J#I.baW#`#L#Z`Q.o`haG`Q#Z`8`W`6.t#h`0`u`0`u`0.r.r.r`0`J`z#X.t`6.t`6#4ax`Y.d.d#`ak.EaY#``w`w.X#Ia`.b.b.b#`#I.b.b`````o`j.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#n``a`ae.d#3aR`v#Ga6#Ia``wae.b.d.JaW`P#1.x.dae.X#`#J`i#C.i.i.i.zajas`1a5`0a5#P.T`T`0`6`6aN#7#R`K#3#`.Kau.#au`B.X`w.da`.ba`.b.b.b#I.b.ba`````.l#m.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U`D``.X`w.xaWa6`v`v.C#Ia``w`w.X.d`wae#1#yae.C.S.d#`#``waW`i.`.y.`aJau`J`J`z`z#7`J`G`z`0`1aj#R.V.H.2.K.#`3`3#K.5a`#`aWa`.b``.b.X.b.b.b.ba``````Iav.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.Uao``#Iae`w.x#3`v`4.C#Ia``waea`.d`w#`.6`B.l#1.L.#.a.o.l.dak.wap.K.K`i.a..ad.T`l`O.W.L.#`F.`.o#3.K`5.Bal#7..`P.6.b.b#3.b.b.b.b.b.b.b.b``.b.b``.X`a.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.UaiaL``.b#I#I.daW#3`v.C#Ia`#I#I.X.Hae#I#OaA`wau`l`Ma3`G`W`Oau#5#5`F`F#0.E.Lad`C.T`c`O`F#0`B.K.K`P.#.T#7#Z`p#R#Wa2.C.X#3``.b.X#```.X.Xa```a`a````I`a.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#m.l``.b#I`w.x.C#3`vaW#Ia`.b#Ia`ae`w.b#dam.o#R#E`zajaj`Jal.B#R`F`F.L.L`Q.#...T`l.#.L#0.E`F`Q.L`i#`.l`s.p.o.K`i#N.Sae#J.X.b#I#`a```.Xa```a`.b``.X`a.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.Ua##I.X.b#I#I`w.CaW#3.C#Ia`.b#Ia`#Iae.b#6amaG.y.q#W.L`F`Q`F.V`b.p`i`Q.a`P`O`l`l`C`t`O.L`F.L#LaL#i`o#QaE#w`s#L.o.s`s.baW.b.b#I#`.ba`.b.b``.b```````S.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.D``#I.b#`#`ae.d.x#3.C#Ia`a`#`a`.b`w.J#damap#I.o.2`H`N`K`N`Y`K#w#w`K.#`P`Oar`l...q`P.#.M#Fak`sak.d`U`U#T#z.p.6`#.d``.C.b``ae#I.b``.X.b``.b.b````#r.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.Ua.``#I#I#`#Iae.xae#3`e#Ia```#Ia`.b`w`waG.La1.l#C.3`x`sakaz#x.Uai#p.8al`O`O`M`1`J`c`c#7`6`s#Q.w#w`s`0#faU#1.W.q#8aW.X.d#`.Xae#I.ba```.b````.b````ag.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.UaM``#I.b#`#`.bae.d`e`e#I.Xa`#Ia`.b`wae#I.E.W.Hawa5.z.n`K`E.a#5.W.z#4#X.W`P`G`T.u`t`t#7.t#Z#F`F`F#0`F#R`P..aj.N`c`s.X.C#Ia`#Iae#Ia```#`a```.X`````S.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#Y``.b.b.b.b#`#I.xae.d#I.X.X#I.b.b`wae.b#1aj.C`t`0.z.t.r`u#P#P.t#h.t#X#Z`c`T`0#4`3`7al#h.t`1alalal..`zaN`T`G..ataY.X.x`wa`#Iae#Ia`a`#I.b`````````X.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.8``a`.b``.b#I#`.x.d.x#`.ba`#I#Ia`#I`w.b`F#4#s#Oaq.t`G#X.M#X.t`6.t`0`G`7ad`G`0#Paladal`1`6#X`1....`z`1.M.M`Gaj.OaY#I.2.x``#`ae#Ia```.b.b``a`.b```R.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#H``.b.b``.b.b#Iae`w.x#I.b``#Iae.b#Iae#I.Kan`7#1aS.t`6.t.t.t.t.t`6#X.T`t..`Ma5a5al`tal..#X`0`6`6#X.M.M#X`0`Ta7.O.V.X`w.d``#Iae#Ia```a```````a````2.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.1aL``#I.ba`.b.b#Iae`wae#I#Ia`.b`w.b#Iae#I`4`MaK`p#X`6.t`6`6.t.t.t#X`G`J.Nad`M`ua5al.Namal`T`T#X#X`6#X#XaN.M`Taj`J`i.X`w`e``#Iae.b``a`.b``````.X``#V.U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#m`o``#I.b``.b.b.b`wae`w#I#I.X.b`w.b.b`w#`.Cajay.k.m`6`6.t.t.t.t`6a3`l..adamara5`0ad`7alam#4`G`0#X#Xa3#XaNaN`T`JaH.V.Xaeaea`#``w#Ia```.b``a```````#w#b.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#f`I``ae.la`.X.b.b`w`wae#I#`a`.b.x#`.b#``I.dat`G#CaN`6#X`6.t.t.t`6.4`Jam..`lar`0a5`J.N`c.T.u#4`GaN`0`TaN#Xa3#P`Ja4ap#I#`.d``.bae#Ia`a`.b``a```a```aL`j.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U`a`I``.8.8``a`.X.bae`w#I#`#`.b```w`w.b#`#I.x.a`G`d#P#X#X`6.t.t.t#X`l`Jam`C`zar`0a5`zaladad`Jar#4`G`G`G`T`T`G`zata4ap`I#I.x``.b#I.ba```.b``a`.b`````o#m.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#e.X``aa#k````.b.b`waeae#I#`.ba`ae`w.b.b#I.d.0.m#E`m.Ma3#X#XaSaq#X`G`lam`z`z`T`0`0#4.N`O`7.Najar`z#4#4`M`1.4`J`caA.p.J#I`ea`.b#`.ba```a`````.Xa````I`U.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.Uag`````D`D````.b.b#I`w#I#`#I.ba``w`w.b.b.b`s.oa7#j#E`M`Taf#X#X#X#X`z..`G`u.4`6.r.r`z`Jad`P.qad`C`J.Taj.u`lam.N#AaZaR#`#`.C.X.b.b.X.X````````.b.X```Iav.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.Uag`````X#n````.b#`#Iae#``w#`.ba`.b#`#I.b.X`s.V.a.7as`z#4`T`G.M.M`G.Tam`z`T`z.t#h.t`l..`J`O`B#y`7.N`C..amamad`c`O.qaR`w#I`e.b.Xa`.b.X``a`````.b.b```I`a.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#e.X``.Dag````.b#I#`#I#``w#I.ba````w#`#I.b.x.K#san`W.4.4`M`G`T`T.Mad`q`P`O`C`z#X#X...L.L.Lak#0`O`c`c`C...N`7`c.R#W`4#`#I`e.b``.b.b.X``a`````.X#Ia`.X`a.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.Uav`I``agav.Xa```ae#I#`#I#`#I.ba`a`.J#Iae.b`wa1.0a8.O.4.u.4ar#4`G.4#4`q#Gak.s#R.W#ZaX#`ak`i.o`q.R`O`c#uad.N`c`g`OaZ.C#`#I.d.ba`.b.X.b````````.b#```.X.D.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#m.l```a#m.l````#`#`#`#I`w#I.b.b``.b#I.x#`#I#vaX#O.O#4.4`z.4ar`G.4`1`G.q.s`i.0`5#0#Gak#N.R`c`g`c`c`c`7.N`c`c.W`OaZ`sae#Iae.b``#`.b.ba`````````.b.X``.D.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U#m`o`Iav`j`Z````.bae#I#I`w#I.b.ba`.X.b.d`w#I`4.`.`a8`M`zar.4#4`M`1.M#X#X#4..#1`i.0#8`7.Nar`l.A.N`tadad#u`7.W`g`O#K.d`w#I#I.b.X#I.b.b``.b``````.b.X``#n.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.Uah`I.l#m.U`H````.X`w.b#I#I`w#I.ba`.b.X`w.C.b#3#0#1au`M`z.4.u.u.u.M#X#X`6a5`zad`c.N`7.u`z`l`lalad#uad#u.N.N`c.#.Wa2.dae#I`w.b.b#`.b.b``.X``````#``I```X.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.1`Z.l#m.Uaa``````ae.b#`#I#I#I.b.b.Xa`.b.d#`.xaI#0#0#E`z.u..`P.W#7`u.t.t`6`G.T.N`7.N`l`zar`lad`C`7.Nadad`7`c.W`tauae.x`wa```.b#I.b.b``a````````w.l```R.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U`H.l#m.U.Y```````w.b.b#``w#I#`.ba`.X``.d`w`w.K.`aG.B`M.u.u.a`B#R`J`1aN.t.ta3...N#R.W`c`J...W`P`F`O.W.N.N`7`7#Z.vae`e#I.Xa`.b#I.b#```````````.l.l``aoai.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U`H`I`U.Uag```````Y.2a`#I#I`w#I.ba`.Xa`.b`w#`.s.v.yau.4.4#P`Taj#O`Bau.#`O.I#Rax.L`F#0.K.V#L.2.p#0`c`tad`7`c#C.G`#`w`e#`a```.b#`.b#Ia`````````.l.l```H.1.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.UaP`Ia#.Uav.l`````R#Ya`#`#Iae`w.ba`.X``a`#`#I#G#q`8.yaj`1.4`T#P#P.u`t`Q.6.a#0#0`B.K#0`i.p`i`F`O`c.N`t.W`7`7`d`O#L`w.d.b````.X.b.b.b``````````#``o```bai.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U`f``#e.U`j`Z````#Va.``.b#I#Iae.ba`.X.X``a`#I.d.KaVaV..`z#4#4`T#4`M####`M.M.tafar.A`O.#`P`q.W.N`7#Z`t`7.W`3#R.V`4#I#I#Ia`````.b.X#Ia``````````I.l``.g.U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#l``ag.U.U.g`````H`X.X.b#`#I#I#`.b.X.X``.b``.J`v`Badal.4`z`G.M`Taf#4`r#.#.`lam.A`c.N`Q#N`5`O.W`c`t`7`7.B#Z.Eae#L`I.b#`a```.b#`.b#Ia`````````.X`I``#w#x.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U`.``.D.U.U`.````.Fac`oa`#`#I`w#I.ba```````a```aW.o#R.u.4#4`G`Ta3af.7`T.u.N`5.0.s.E#0`5.q`O`c.W`c`8`t.B#R`B.l.S`s.b#I#Ia```.X.b.b#Ia```a``````I`I```Hai.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.UaO```k.U.U.D`````I.D.8a`.b#I#I#I.ba`.X``a```a`#`.C`#`c.u.e`G`T#X#Xa3`Mar`l`7`P`q#8.L`O`c`g`c`c`c.B#Z#Z#0.2.2#Lae.b#`#`a```.X.b.X.b``a```````.X`I```o#m.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.D``.Y.U.Uah`o````.D#k``.b#`#I`w#Ia`.X.X``a```.b#I#v`#`7.u`1`G.M#X`6`6.t`6`T`G`z.u...Nad`c.W`c.Bal#Z`F.H.H`saRae#``w`wa`a`.b.X``.Xa`````````.X.X``.l#m.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.D``aM.U.Uai`b````.Y#n``a`#`#I#I#`a`a`a```#`a```.b.C`#`F`c.u`M`T#X#X.t`6.t`6.M`G.4.u.u.T.N`7`t.k#Z#5ak#`.C#G.S.d.x`e`wa```a```a`a```a`````````.X``.lah.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#e``#g.U.U.U#g`````R.D``a`.b#`#I`w.b``a```ae`wa`.bae#v.`#6al.u`Gaf#X#X#X`6.t`6`G#4ar`lar.A`7.B.G`Q.o#`ak.S.S.oae.d.C`wa`.b.X``a```a```a`````a`````.l`U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.Uav`I`2.U.U.Uac.X``#w#p`I``.b#`#I#I.ba`````.b.H.b.b#`ap.f.6`F`C`J.u`G#X#X#X#X`T`Taf`M.u.u.B.W.B#5.S.2.d.w#Lap.oaeaW#3.x``.b.b``a```a`````a```a`````.l#m.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#m.l.g.U.U.Uav`o``.H`X.la`.b.b`w#I.ba`a```a`ae.b.X#``i.5`F#y`Fad`J`J.u`T.M`G`T`1`zar`zad#Z#R`Q.o`o#J#L#L#G#v.o`w#3`v`w``.X.X``````a`a`.b``````````.l`U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U#b`Z`H#x.U.U.1#w````aM`Z``a`#`#I.b.ba```a```#I.X.b.ba6.c.``5`5`F`c`J`Jad`Jaj.G`t.W.A...##R`F.o.2ak#G#Lap.0#vap.x`v#3a````I.J.X````````.X.X````a````I`U.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U`Y`N#b.U.U.U`.````ao`o.ba`#I#`.b.ba```a```ae.b.b.X.H#M`#.y`Q`5.0`P#8#R#Z#R.W#R#R#R.L`5.f.o.d#L.oapap#v#v.0.S`w`w.J.l.X.b#Ia`````a```.X.X``.X````.Xag.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U`R.H#m.U.U.U`a`I```Z.l``.b#I#`.b.b``a`a```aea`.H`w.baGa2.h#y#8`P#0.K.s#0`5.``B.`.s.V.o#L#L`i`i.o#v.0ap#v#G.d.Xak`b#```.X.b``````a```a```a```a`````#n.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#n.l`U.U.U.Uab`Z``#I.ba`.b.b#`.b.b.b``.X``#Ia`ae#J`IapaF.y#W#y`q`P.L#0.0.s.o.o#G`s#3`i.s`E.0.f.0.0#vap.CaW.H`o`b`Z.X````#`.X``````a```.X.b``a`````#l.U.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U#f`Z`a.U.U.U.U`2``.b.b``#I.b#I.b.b.b``.X.ba```.Ha6.da6aFa2a2#W.6`5`5.6#0`F`F`F#0#0.s.0.0.0.K.0#v.o.S`s#w`Y.2.w`Z.l.b````.b.X````.X``a```a`````````aP.1.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.Uai#wag.U.U.U.U#n``.X.X``.b#I#`.b.b.b``.X.b`````w.o.CaW#M#5a2#WaF.h#0#6#6`F`5#0`B.K.0.0.s#v.0#v.p`Y#VaEaa#V`o`o.H.2`I``a``I.X``````a```a```#Ia``````Ia#.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#gac.U.U.U.Ua#.X.Xa```#`#I#`.b.b``a`a```````.J.0a6.Ca1#W#5.v#W.v.5`E.5.5`##0`B`B.f.K.0#U.0.paa#l#k#kaa.p#`.l.H`o.b````#I.X````#`.X.X``a`.X.X```````k.U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uac.Y.U.U.U.U`V`Z``.b.b.b#I#`.b.b.b````a`````.X#v.o.C.pa2#q#W#q#RaF#U#U.f.s`B#U#U`E#Uap`4.Ea..Ya.#k`n#w`o.J.H.l.F.J````.X``````#```a```````.b```````fai.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`a`D.U.U.U.U.U#V``.X.b.bae#I.b.b.Xa`a`.b``.X.X.o#UaWa6`h#W.v#R#A#A#8#N`B.5`B`B`B`E`v`i#o`S.Ya.#k.g.p.w.l#`.H.H.J.b````.b.b.X``.X.X.X````a```a``````Z`U.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`U`f#x.U.U.U.U`D``a`#I.b#I.b.b.ba```````a```.X`v`#.p`4#1#5#5#W#q#qaA.R#M`#aGaG.sa6#s#c.U#c.Y#k.gaL`Z`o.J.l.H.ba`````````.b````.X````a```a`````.X``a`.Y.U.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`j#kai.U.U.U.U.D````.b.b#`.b.b``a```````.l#```#3#NaG`sa1#qa2a2#A#WaZaAaZ#d#N#v#G#T#c.U.U#i#l.g`s`o.2`Z.l#`a`.X``.X``````.X.X````a```a`````````.X`````H#m.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.Uai#k#c.U.U.U.U`U`o``.b.b.b.X.b.b``a``````o.l``.J.0#M`s#L#5#q#y#WaZaF#8aZ`yaIa.#c.U.U#b#n#l#V.w.F`Z.w.H``````.X`I``````.X.b``a`.X``.b.b.X``````.X.X````.D.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`R`U.U.U.U.U.U#w````#`.b``a```.X``````.l.l`o`oa6#N.V`s.`#W#y#AaFaFaF#N.y#c.U.U.U#c#i#l`f.g.w#B.H.X``````````````````#`.H.x.Xa```.X.X.X.b.b.X``#I`````f.U.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U`.av.U.U.U.U.U`.````.b``a```a`.X``````#`.F`I.l#`aGaG`s.V#Wa2.v.R#N#va2.U.U.U.U`U#ia.#kaa.g#B`I.X#I.X.H`saWaeaW.d````a`.b`I.b``````a`.bae#I``````.b``.Xag.U.U.U.U",
".U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U#n`a.U.U.U.U.U`A.X``.b````a```.X.X````.l`o.X`b.Xa6#Na6a6#yaZ.c#UaWa.#c.U.U.U`U#o.Y.Y#l#z.w.H`w.H.J#``w.x`s.d`w`s.b````a```a`a`.b.b.X.b.d`w.b``````.X``aL#eab.U.U"
};
